/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.mp.client;

import edu.duke.ece651.mp.client.controller.loader.LoginRegisterControllerLoader;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;

import java.io.*;
import java.net.URL;
import java.nio.file.Paths;

public class Client extends Application {

  /* network input output object stream  */
  public static Player player;
  MediaPlayer m = MusicFactory.createBGMPlayer();

  @Override
  public void start(Stage stage) throws IOException, ClassNotFoundException {

    /* connect to the remote */
    player = new Player("vcm-24767.vm.duke.edu", 12345);

    stage.setResizable(false);  //set window resizable ato false

    m.setAutoPlay(true);
    m.setCycleCount(MediaPlayer.INDEFINITE);

    //load the fxml
    LoginRegisterControllerLoader loginRegisterControllerLoader = LoginRegisterControllerLoader.getLoginRegisterControllerLoader();
    AnchorPane gp = (AnchorPane) loginRegisterControllerLoader.getParent();

    Scene scene = new Scene(gp, 1280, 920);
    URL cssResource = getClass().getResource("/ui/style.css");
    scene.getStylesheets().add(cssResource.toString());
    stage.setScene(scene);
    stage.show();
  }

}
